---
name: Decertify Synapse User

on:
  workflow_call:
    inputs:
      USER_ID:
        required: true
        type: string
        description: ID of the user to decertify

jobs:
  ensure-runner-exists:
    uses: "./.github/workflows/ensure_shared_runner_exists.yml"
    secrets: inherit

  execute-script:
    runs-on: ${{ needs.ensure-runner-exists.outputs.LABEL }}
    needs: [ensure-runner-exists, get-env]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: Sage-Bionetworks/synapse-ops-core
          ref: main

      - name: Execute script
        run: scripts/decertify_user.sh ${{ inputs.USER_ID }} ${{ vars.SYNAPSE_HOST }}
...
