---
name: Delete Cloudformation Stack

on:
  workflow_call:
    inputs:
      STACK_NAME:
        required: false
        type: string
        default: prod-999-shared-resources
        description: The name of the Cloudformation stack that needs to be deleted

jobs:
  ensure-runner-exists:
    uses: "./.github/workflows/ensure_deployment_runner_exists.yml"
    secrets: inherit

  execute-script:
    runs-on: ${{ needs.ensure-runner-exists.outputs.LABEL }}
    needs: ensure-runner-exists

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: Sage-Bionetworks/synapse-ops-core
          ref: main

      - name: Execute script
        run: scripts/delete_cloudformation_stack.sh ${{ inputs.STACK_NAME }}
...
