---
name: Create (or verify the existence of) a self-hosted runner for small jobs that require a Synapse Admin PAT

on:
  workflow_call:
    outputs:
      LABEL:
        value: ${{ jobs.ensure-runner-exists.inputs.LABEL }}
jobs:
  ensure-runner-exists:
    uses: "./.github/workflows/ensure_runner_exists.yml"
    with:
      LABEL: 'shared-runner'
      INSTANCE_TYPE: 't4g.small'
      CONTEXT: ${{ vars.CONTEXT }}
      ROLE_TO_ASSUME: ${{ vars.ROLE_TO_ASSUME }}
    secrets: inherit
...
