---
name: Create (or verify the existence of) a self-hosted runner with SYNAPSE_DEPLOYMENT_ROLE

on:
  workflow_call:
    outputs:
      LABEL:
        value: ${{ jobs.ensure-runner-exists.inputs.LABEL }}
jobs:
  ensure-runner-exists:
    uses: "./.github/workflows/ensure_runner_exists.yml"
    with:
      LABEL: 'deployment-runner'
      INSTANCE_TYPE: 't4g.large'
      CONTEXT: ${{ vars.CONTEXT }}
      ROLE_TO_ASSUME: ${{ vars.ROLE_TO_ASSUME }}
      SYNAPSE_DEPLOYMENT_ROLE: ${{ vars.SYNAPSE_DEPLOYMENT_ROLE }}
    secrets: inherit
...
