---
name: Migration, Prod to Staging

on:
  workflow_call:
    inputs:
      STACK:
        required: true
        type: string
        description: dev or prod
      REMAIN_READ_ONLY_MODE:
        required: true
        type: boolean

env:
   RUNNER_LABEL: migration-runner
   INSTANCE_TYPE: t4g.large
   PATH_TO_SCRIPT: scripts
   PATH_TO_SOURCE_CODE: src

jobs:
  # this is necessary to make env values available to later jobs
  get-env:
    runs-on: ubuntu-latest
    steps:
       - run: echo "null"
    outputs:
      RUNNER_LABEL: ${{ env.RUNNER_LABEL }}
      INSTANCE_TYPE: ${{ env.INSTANCE_TYPE }}
      PATH_TO_SCRIPT: ${{ env.PATH_TO_SCRIPT }}
      PATH_TO_SOURCE_CODE: ${{ env.PATH_TO_SOURCE_CODE }}

  ensure-runner-exists:
    needs: get-env
    uses: "./.github/workflows/ensure_runner_exists.yml"
    with:
      LABEL: ${{ needs.get-env.outputs.RUNNER_LABEL }}
      CONTEXT: ${{ vars.CONTEXT }}
      ROLE_TO_ASSUME: ${{ vars.ROLE_TO_ASSUME }}
    secrets: inherit

  execute-script:
    runs-on: ${{ needs.get-env.outputs.RUNNER_LABEL }}
    needs: [ensure-runner-exists, get-env]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: Sage-Bionetworks/synapse-ops-core
          ref: main
          path: ${{ needs.get-env.outputs.PATH_TO_SCRIPT }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: Sage-Bionetworks/Synapse-Migration-Utility
          ref: develop
          path: ${{ needs.get-env.outputs.PATH_TO_SOURCE_CODE }}

      - name: Execute script
        run: >
          ${{ needs.get-env.outputs.PATH_TO_SCRIPT }}/scripts/migration_prod_staging.sh
          ${{ inputs.STACK }}
          ${{ needs.get-env.outputs.PATH_TO_SOURCE_CODE }}
          ${{ inputs.REMAIN_READ_ONLY_MODE }}
...
