---
name: Remove Synapse User

on:
  workflow_call:
    inputs:
      USER_ID:
        required: true
        type: string
        description: ID of the user to delete

env:
   RUNNER_LABEL: shared-runner

jobs:
  ensure-runner-exists:
    uses: "./.github/workflows/ensure_runner_exists.yml"
    with:
      LABEL: ${{ env.RUNNER_LABEL }}
      CONTEXT: ${{ vars.CONTEXT }}
      ROLE_TO_ASSUME: ${{ vars.ROLE_TO_ASSUME }}
    secrets: inherit

  execute-script:
    runs-on: ${{ env.RUNNER_LABEL }}
    needs: ensure-runner-exists
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: Sage-Bionetworks/synapse-ops-core
          ref: main

      - name: Execute script
        run: scripts/verify_oauth_client.sh ${{ inputs.USER_ID }} ${{ vars.SYNAPSE_HOST }}
...
