---
name: Unquarantine User

on:
  workflow_call:
    inputs:
      EMAIL_ADDRESS:
        required: true
        type: string
        description: Email Adress to unquarantine

env:
   RUNNER_LABEL: shared-runner

jobs:
  ensure-runner-exists:
    uses: "./.github/workflows/ensure_runner_exists.yml"
    with:
      LABEL: ${{ env.RUNNER_LABEL }}
      CONTEXT: ${{ vars.CONTEXT }}
      ROLE_TO_ASSUME: ${{ vars.ROLE_TO_ASSUME }}
    secrets: inherit

  execute-script:
    runs-on: ${{ env.RUNNER_LABEL }}
    needs: ensure-runner-exists

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: Sage-Bionetworks/synapse-ops-core
          ref: main

      - name: Execute script
        run: scripts/unquarantine_user.sh ${{ inputs.EMAIL_ADDRESS }} ${{ vars.SYNAPSE_HOST }}
...
