---
name: Update feature status

on:
  workflow_call:
    inputs:
      FEATURE_STATUS:
        required: false
        type: boolean
        default: true
        description: true to enable feature or false to disable
      FEATURE:
        required: true
        type: string
        description:  The feature to enable or disable
      STACK:
        required: true
        type: string
        description: Stack to affect

jobs:
  ensure-runner-exists:
    uses: "./.github/workflows/ensure_shared_runner_exists.yml"
    secrets: inherit

  execute-script:
    runs-on: ${{ needs.ensure-runner-exists.outputs.LABEL }}
    needs: ensure-runner-exists

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: Sage-Bionetworks/synapse-ops-core
          ref: main

      - name: Execute script
        run: scripts/update_feature_status.sh ${{ inputs.FEATURE_STATUS }} ${{ inputs.FEATURE }} ${{ inputs.STACK }}
...
